강민지/mytalk_main/login_page/urls.py
from django.urls import path, include
from . import views

app_name = 'login_page'

urlpatterns = [
    path('', views.login_page_view, name='login'),
    path('register/', include('register_page.urls', namespace='register_page')),
    path('main/', include('chatting_main_page.urls', namespace='chatting_main_page')),
    path('login_api/', views.try_login, name='try_log_api')
]

강민지/mytalk_main/mytalk_main/urls.py
from django.urls import path, include
from login_page import views

urlpatterns = [
    path('', include('login_page.urls', namespace='login_page')),
    path('register/', include('register_page.urls', namespace='register_page'))
]

강민지/mytalk_main/login_page/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, email, name, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(email, name, password, **extra_fields)

class Users(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=100, unique=True)
    profile_picture = models.CharField(max_length=255, default='profile_basic.png')
    status = models.CharField(max_length=10, choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='online')
    status_message = models.CharField(max_length=255,null=True)
    
    is_online = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    
    last_login = None
    
    objects = CustomUserManager()
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    def __str__(self):
        return self.name

강민지/mytalk_main/login_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login
from django.http import JsonResponse

user_model = get_user_model()

def login_page_view(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return redirect('/main')
        else:   
            return render(request, 'contents/login.html')
        
def try_login(request):
    if request.method == 'POST':
        user_email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=user_email, password=password)
        if user is not None:
            login(request, user)
            current_user = user_model.objects.get(email=request.user.email)
            current_user.is_online = True
            current_user.save()
            return JsonResponse({'message':'Success'})
        else:
            return JsonResponse({'message': 'Error', 'error': 'login_fail'})
    # return JsonResponse({'message':'Success'})

강민지/mytalk_main/templates/login_page/login.html
{% load static %}
  {% include 'com/Head.html' %}
  <title>LOGIN</title>
</head>

<body class="page_view">
  
  <!--{ include 'com/GNB.html' %}-->

  <div class="main_view login">

    <div class="login--box">

      <div class="login--header">
        <h2 class="form--title">로그인</h2>
      </div>

      <form method="post" id="send_login_user_info" class="login--form">
        {% csrf_token %}
        <input type="text" name='email' placeholder="Email">
        <label for="vision" class="vision">
          <input type="password" name='password' placeholder="Password">
          <input type="checkbox" id="vision" hidden>
          <img src="{% static 'icon/Visibility-off.svg'%}" alt="" class="vision__icon active">
          <img src="{% static 'icon/Visibility.svg'%}" alt="" class="vision__icon deactive">
        </label>
        <!--<div class="button_box">-->
        <input type="submit" value="로그인" name="login" class="btn btn--login">
        <input type="button" value="회원가입" name="register" class="btn btn--register" onclick="location.href='{% url 'register_page:register' %}'">
      </form>

      <div class="form--footer">
        <a href="#">ID/PW 찾기 </a>
        <a href="#">관리자 문의 </a>
      </div>

    </div>

  </div>

  <script src="{% static 'js/login.js' %}"></script>
</body>

</html>