강민지/loginchat/chatbot/urls.py
from django.urls import path
from . import views

app_name = 'chatbot'

urlpatterns = [
    path('', views.chatbotView, name='chathome'),
    path('chatting/', views.sendChatBody, name='chatting'),
]

강민지/loginchat/login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('signup/', views.signupView, name='signup'),
    path('chatbot/', include('chatbot.urls', namespace='chatbot')),
]

강민지/loginchat/loginchat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),
]

강민지/loginchat/chatbot/models.py
from django.db import models

class MessagesWithChatBot(models.Model):
    class Meta:
        db_table = "MessagesWithChatBot"
    speaker = models.CharField(max_length=30)
    chat_text = models.TextField()

강민지/loginchat/login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Users(AbstractUser):
    name = models.CharField(max_length=30)

강민지/loginchat/chatbot/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
import os
import json
import nltk
import numpy as np
from nltk.stem.lancaster import LancasterStemmer
from .models import MessagesWithChatBot
from tensorflow.python.framework import ops
import random
import tflearn
# nltk.download()

stemmer = LancasterStemmer()

def getDataSet():
    words = []
    labels = []
    docs_x = []
    docs_y = []
    training = []
    output = []
    with open(os.path.join('static','json/intents.json'), encoding='UTF8') as file:
        data = json.load(file)
    
    for intent in data['intents']:
        for pattern in intent['patterns']:
            wrds = nltk.word_tokenize(pattern)
            words.extend(wrds)
            docs_x.append(wrds)
            docs_y.append(intent['tag'])
        
        if intent['tag'] not in labels:
            labels.append(intent['tag'])

    words = [stemmer.stem(w.lower()) for w in words if w != "?"]
    words = sorted(list(set(words)))

    labels = sorted(labels)

    out_empty = [0 for _ in range(len(labels))]

    for x, doc in enumerate(docs_x):
        bag = []
        wrds = [stemmer.stem(w.lower()) for w in doc]
        
        for w in words:
            if w in wrds:
                bag.append(1)
            else:
                bag.append(0)
                
        output_row = out_empty[:]
        output_row[labels.index(docs_y[x])] = 1
        
        training.append(bag)
        output.append(output_row)

    training = np.array(training)
    output = np.array(output)
    
    return words, labels, training, output, data

def bag_of_words(s, word):
    bag = [0 for _ in range(len(word))]
    
    s_words = nltk.word_tokenize(s)
    s_words = [stemmer.stem(w.lower()) for w in s_words]
    for se in s_words:
        for i, w in enumerate(word):
            if w == se:
                bag[i] = 1

    return np.array(bag)

def printAnswer(chat_txt):
    isTraining = False
    ops.reset_default_graph()
    
    words, labels, training, output, data = getDataSet()

    net = tflearn.input_data(shape=[None, len(training[0])])
    net = tflearn.fully_connected(net, 8)
    net = tflearn.fully_connected(net, 8)
    net = tflearn.fully_connected(net, len(output[0]), activation='softmax')
    net = tflearn.regression(net)

    model = tflearn.DNN(net)

    if isTraining:
        model.fit(training, output, n_epoch=1500, batch_size=8, show_metric=True)
        model.save('static/train.h5')
        isTraining = False
    model.load('static/train.h5')

    results = model.predict([bag_of_words(chat_txt, words)])
    results_index = np.argmax(results)
    tag = labels[results_index]
    
    for tg in data['intents']:
        if tg['tag'] == tag:
            responses = tg['responses']
            
    return random.choice(responses)

def sendUserChat(request, question):
    MessagesWithChatBot(speaker='user', chat_text=question).save()
    return HttpResponseRedirect(reverse('login:chatbot:chathome'))

def sendBotChat(request, question):
    answer = printAnswer(question)
    MessagesWithChatBot(speaker='chatbot', chat_text=answer).save()
    

def sendChatBody(request):
    if request.method == 'POST' and request.POST['userTxt'] != '':
        question = request.POST['userTxt']
        sendUserChat(request, question)
        sendBotChat(request, question)
    return HttpResponseRedirect(reverse('login:chatbot:chathome'))
    
def chatbotView(request):
    messages = MessagesWithChatBot.objects.all()
    messages = {"messages":messages}
    return render(request, 'chatbot/chatbot.html', messages)

강민지/loginchat/login/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth import authenticate, login, logout
from .models import Users
import json

def loginCheck(request):
    if request.user.is_authenticated:
        return True
    else:
        return False

def loginView(request):
    if request.method == 'GET':
        loginCheck(request)
    elif request.method == 'POST':
        userID = request.POST['userID']
        userPW = request.POST['userPW']
        user = authenticate(username=userID, password=userPW)
        if user is not None:
            login(request, user)
    if loginCheck(request):
        return redirect('/chatbot')
    else:
        return render(request, 'login/login.html')
    
def logoutView(request):
    logout(request)
    return redirect('login:login')

# def getUserModel(request):
#     usermodel = Users.objects.all()
#     context = {
#         "users":usermodel,
#         "user":json.dumps([user.json() for user in usermodel])
#     }
    
#     print(context)

def signupView(request):
    # usermodels = getUserModel(request)
    if request.method == 'POST':
        userID = request.POST['userID']
        userPW = request.POST['userPW']
        userName = request.POST['userName']
        userEmail = request.POST['userEmail']
        
        # user = Users.objects.create_user(userID, userEmail, userPW)
        # user.name = userName
        # user.save()
        return redirect('login:login')
    return render(request, 'login/signup.html')

강민지/loginchat/templates/chatbot/chatbot.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ChatBot</title>
    <link rel="stylesheet" href="{% static 'css/chatbot.css' %}">
    <script src="https://kit.fontawesome.com/77ad8525ff.js" crossorigin="anonymous"></script>

</head>
<body>
    {% if not user.is_authenticated  %}
    <script type="text/javascript">
        alert("로그인이 필요합니다.");
        location.href = '{% url "login:login" %}';
    </script>
    {% else %}
    <div id="chat_list">
        <input type="button" value="LOGOUT" id='btn_logout' onclick="location.href='{% url 'login:logout' %}'">
    </div>
    <div id='chat_form'>
        <form action='chatting/' method="post" id='chatting'>
           {% csrf_token %}
            <div class='chat_top'>CHATBOT</div>
            <div class='chat_body'>
            {% comment %} <div class="user_icon"><i class="fa-thin fa-circle-user"></i></div>
                <div class='user_text'>유저입니다. 안녕하십니까</div>
                <div class="bot_icon"><i class="fa-soild fa-robot"></i></div>
                <div class='bot_text'>봇입니다.  중</div> {% endcomment %}
                {% for message in messages %}
                    {% if message.speaker == 'chatbot' %}
                    <div class='bot_text'>
                    {% else %}
                    <div class='user_text'>
                    {% endif %}
                {{message.chat_text}}</div>
                {% endfor %}
            </div>
            <div class='chat_bottom'>
                <input type="text" name="userTxt" id="" placeholder>
                <input type="submit" value="SEND" from='chatting'>
            </div>
        </form>
    </div>
    {% comment %} <div id="online_user">zxczxczxc</div> {% endcomment %}
    {% endif %}
</body>
</html>

강민지/loginchat/templates/login/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Need Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <script src="{% static 'js/login.js' %}"></script>
</head>
<body>
    {% if not user.is_authenticated and request.method == 'POST' %}
        <script>loginFail("ID 또는 비밀번호가 맞지 않습니다.");</script>
    {% endif %}
    <div class='login-wrapper'>
        <h1>LOGIN</h1>
        <form action="" method="post" id='login-form'>
            {% csrf_token %}    
            <input type="text" name="userID" placeholder='ID'>
            <input type="password" name="userPW" placeholder='PASSWORD'>
            <input type="submit" value="LOGIN">
            <input type="button" value="SIGNUP" onclick="location.href='{% url 'login:signup' %}'">
        </form>
    </div>
</body>
</html>

강민지/loginchat/templates/login/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class="signup-wrapper">
        <h1>SIGN UP</h1>
        <form action="" method="post" id='signup-form'>
            {% csrf_token %}
            <input type="text" name="userID" placeholder='ID' id='userID' class='input-none-box' onkeyup='idCheck();' onblur='idOverlapCheck();' maxlength='30'><br>
            <span id='verifyID' class='input-none-text'>영문으로 시작하는 영문, 숫자 조합 6~20자리</span>
            <input type="password" name="userPW" placeholder='PASSWORD' id='userPW' class='input-none-box' onkeyup='pwCheck();pwIsSame();' maxlength='25'><br>
            <span id='verifyPW' class='input-none-text'>영문, 숫자, 특수 문자가 포함 8~16자리</span>
            <input type="password" name="confirmPW" placeholder='CONFIRM PASSWORD' id='confirmPW' class='input-none-box' onkeyup='pwIsSame();' maxlength='25'><br>
            <span id='isSame' class='input-none-text'> </span>
            <input type="text" name="userName" placeholder='NAME' id='userName' class='input-none-box' onkeyup='nameCheck();' maxlength='25'><br>
            <span id='verifyName' class='input-none-text'>이름을 입력해주세요.</span>
            <input type="email" name="userEmail" placeholder='EMAIL' id='userEmail' class='input-none-box' onkeyup='emailCheck();' maxlength='30'><br>
            <span id='verifyEmail' class='input-none-text'>이메일 주소를 입력해주세요.</span>
            <input type="submit" value="Sign Up" id='btn_submit' onclick='verifyInput();'>
        </form>
    </div>
    <script src="{% static 'js/login.js' %}"></script>
</body>
</html>