강민지/Django/loginpage/loginpage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

강민지/Django/loginpage/users/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('', views.loginView, name="login"),
    path('logout', views.logoutView, name="logout"), 
    path('signup/', views.signupView, name="signup"), 
]

강민지/Django/loginpage/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    user_id = models.CharField(max_length=10)

강민지/Django/loginpage/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .models import User

def loginView(request):
    if request.method == 'POST':
        userID = request.POST.get('userID', '')
        userPW = request.POST.get('userPW', '')
        user = authenticate(username= userID, password = userPW)
        if user is not None:
            login(request, user)
        else:
            pass
    return render(request, 'user/login.html')


def logoutView(request):
    logout(request)
    return redirect("user:login")

def signupView(request):
    if request.method == 'POST':
        username = request.POST.get('userID', '')
        password = request.POST.get('userPW', '')
        lastname = request.POST.get('lastname', '')
        firstname = request.POST.get('firstname', '')
        email = request.POST.get('email', '')
        
        user = User.objects.create_user(username, email, password)
        user.last_name = lastname
        user.first_name = firstname
        user.save()
        return redirect('user:login')
    
    return render(request, 'user/signup.html')

강민지/Django/loginpage/users/templates/user/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LOGIN</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% if user.is_authenticated %}
    <div class='access-wrapper'>
        <h1>LOGIN SUCCESS</h1>
        <h2>{{ user.username }}님 환영합니다.</h2>
        <input type="button" value="Logout" id="btn-logout" onclick="location.href='{% url 'user:logout' %}'">
    </div>
      
    {% else %}
        {% comment %} {% if method == POST %}
        <script>
            alert("ID 또는 비밀 번호가 맞지 않습니다.");
        </script>
        {% endif %} {% endcomment %}
    <div class='login-wrapper'>
        <h1>LOGIN</h1>
        <form action="" method="post" id="login-form">
            {% csrf_token %}
            <input type="text" name="userID" placeholder="ID">
            <input type="password" name="userPW" placeholder="PASSWORD">            
            <input type="submit" value="Login">
            <input type="button" value="Sign Up" onclick="location.href='{% url 'user:signup' %}'">
        </form>
    </div>

    {% endif %}
    
</body>
</html>

강민지/Django/loginpage/users/templates/user/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SIGN UP</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="signup-wrapper">
        <h1>Sign Up</h1>
        <form action="" method="post" id="signup-form">
            {% csrf_token %}       
            <input type="text" name="userID" placeholder="ID">
            <input type="password" name="userPW" placeholder="PASSWORD">
            <input type="text" name="lastName" placeholder="LAST NAME">
            <input type="text" name="firstName" placeholder="FIRST NAME">
            <input type="text" name="email" placeholder="EMAIL">
            <input type="submit" value="Sign Up">
        </form>
    </div>
</body>
</html>